//
//  TDSSDKConstants.h
//  TDSSDK
//
//  Created by Bottle K on 2021/2/25.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXTERN int const ERROR_CODE_NORMAL;
FOUNDATION_EXTERN int const ERROR_CODE_NOT_INIT;

FOUNDATION_EXTERN int const ERROR_CODE_BIND_CANCEL;
FOUNDATION_EXTERN int const ERROR_CODE_BIND_ERROR;

FOUNDATION_EXTERN int const ERROR_CODE_LOGOUT_LOGIN_STATE_INVALID;
FOUNDATION_EXTERN int const ERROR_CODE_LOGOUT_USER_CENER_LOGOUT;
FOUNDATION_EXTERN int const ERROR_CODE_LOGOUT_GAME;

NS_ASSUME_NONNULL_END
